version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Passw0rd123
    volumes:
      - ./local/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./local/pgadmin:/var/lib/pgadmin
